### ISSUE TITLE
Securing serverless applications with the right IAM permissions 

### ISSUE THREAD

**Issue by apierr** [devw/stag-sls#2]
- [ ] add serverless-iam-roles-per-function ... https://www.npmjs.com/package/serverless-iam-roles-per-function
- [ ] deploy it

````
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - s3:PutObject
        - se:GetObject
      Resource: 
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.tableName}
        - arn:aws:s3:::${self:provider.environment.bucketName}
    - Effect: Allow
      Action: 
        - dynamodb:Query
      Resource: 
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.tableName}/index/*
```
