### ISSUE TITLE
Request optional path parameter

### ISSUE THREAD

**Issue by apierr** [devw/stag-sls#9]
```
  get:
    handler: lambdas/endpoints/read-db.handler
    events:
      - http:
          path: /{PK}/{SK?}
```
